import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";

import localfont from "next/font/local"
import { Providers } from "@/components/providers";




const regular = localfont(
  {
    src: [
      {
        path: "../OTF/GeneralSans-Regular.otf"
      }
    ],
    variable: "--font-regularGeneral"
  }
)




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={`${regular.variable} font-regular-sans`}>
          {children}</body>
      </Providers>

    </html>
  );
}
